image: docker:stable

stages:
  - build

variables:
  CLIENT_IMAGE_NAME: $CI_REGISTRY_IMAGE/eat-client:$CI_COMMIT_REF_SLUG
  API_IMAGE_NAME: $CI_REGISTRY_IMAGE/eat-djangoapp:$CI_COMMIT_REF_SLUG

build_client_image:
  stage: build
  script:
    - docker build -t $CLIENT_IMAGE_NAME  .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $CLIENT_IMAGE_NAME
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: $BASEURL
  only:
    - staging
    - production
    - tags

build_api_image:
  stage: build
  script:
    - docker build -t $API_IMAGE_NAME -f eat_archive/Dockerfile .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $API_IMAGE_NAME
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: $BASEURL
  only:
    - staging
    - production
    - tags

