apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eat

namePrefix: eat-

bases:
  - ../../base/

resources:
  - ingress.yml

patchesStrategicMerge:
  - env.yml

secretGenerator:
- name: backend
  literals:
    - secret_key=super_secret

commonLabels:
  stage: development

images:
  - name: gitlab.sciences-po.fr:4567/medialab/eat_datascape/eat-backend
    newTag: 'master'
  - name: gitlab.sciences-po.fr:4567/medialab/eat_datascape/eat-frontend
    newTag: 'master'
