apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend/pvc.yml
  - backend/deployment.yml
  - backend/service.yml
  - frontend/deployment.yml
  - frontend/service.yml

commonLabels:
  owner: medialab
  app: eat
